name: update GitHub Pages

on:
  push:
    branches:
      - master # 更改为你使用的主分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出文档仓库
        uses: actions/checkout@v2

      - name: 克隆网页仓库
        run: git clone https://github.com/Riko-Tu/riko-tu.github.io.git

      - name: 复制docs目录内容
        run: cp -R docs/* riko-tu.github.io/

      - name: 推送到网页仓库
        run: |
          cd riko-tu.github.io
          git config user.name "Turan"
          git config user.email "lisiai797@gmail.com"
          git add .
          git commit -m "自动更新来自turnaBlog的内容"
          git push https://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:x-oauth-basic@github.com/Riko-Tu/riko-tu.github.io.git
